# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-IxIMzzJKCVZdibSok3cdPNN6mf1eTss
"""

import sympy as sp
import numpy as np
import matplotlib.pyplot as plt
def evaluar(x):
    return x*x*x*x
x = sp.Symbol('x')
y = x**4
concava="";
print ("Determine la concavidad de la gráfica de f(x) = x**4 en x = 0. ")
print("El resultado de la primera derivada es: ")
print(sp.diff(y,x))
f=sp.diff(y,x,x)
print("El resultado de la segunda derivada es: ")
print(f)
rango = np.linspace(-10, 10, 41)
evalua=[]
res=[]
for i in rango:
    values = {x:i}
    res.append(f.evalf(subs=values))
    evalua.append(evaluar(i))
for j in res:
    if(j==0):
        concava="sin conclusion"
        break
    else:
        if(j>0):
            concava="hacia abajo"
        else:
            concava="hacia abajo"
print("La concavidad de la funcion es: ",concava)
plt.plot(rango, evalua)
plt.show()